### ISSUE TITLE
大神，有时间 能再写个类似网页收藏夹的插件不

### ISSUE THREAD

**Issue by songxing10000** [bugEnding/HHEnumeration-Xcode#1]
在一个大项目里，有时候可能会经常在其中跳来跳去的，但是又想在几个常用的文件里写代码，能收藏这几个常用 文件吗

**Comment by huaxi** [comment]
嗯，有时间先把，叫我大神不敢当啊😱，其他理论的知识点我还没学完呢,有空我在研究下你这个吧

**Comment by liujuliuju521** [comment]
I cann't wait to try.but...

**Comment by huaxi** [comment]
对了，不是可以双击打开新的代码编辑窗口吗，
