### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by liujuliuju521** [bugEnding/HHEnumeration-Xcode#2]

**Comment by huaxi** [comment]
and then?

**Comment by guillaume-algis** [comment]
😂 ahah wtf. That's nice I guess, but still... wtf.

**Comment by huaxi** [comment]
She‘s a nice girl,and one of my best good friends,Please DON'T use some unfriendly words on this issue, or something else, OK?！ I don't care if it is just an abbreviation，I will delete the abbreviation...

**Comment by guillaume-algis** [comment]
@huaxi I'm truly deeply sorry if I hurt anyone's feelings here, I just found opening a Github issue only to say "good job" was amusing.

Again, sorry, I'll amend the comment :)

**Comment by huaxi** [comment]
It's OK 😌

**Comment by huaxi** [comment]
hey, I will delete our conversation,   as I said  she a nice girl , I hope you have no comments 😀

**Comment by guillaume-algis** [comment]
Absolutely fine :)

**Comment by huaxi** [comment]
妹子，good 应该首字母大写的 才是😱

**Comment by liujuliuju521** [comment]
You should speak English with me.

**Comment by huaxi** [comment]
don't you know I'm not good at English?
