### ISSUE TITLE
Would be cool if you added this plugin to Alcatraz

### ISSUE THREAD

**Issue by Quarezz** [bugEnding/HHEnumeration-Xcode#3]
https://github.com/supermarin/Alcatraz#i-want-to-submit-my-package

**Comment by guillaume-algis** [comment]
Seconded :+1: 

Alcatraz makes installing plugins simpler, I looked there first after reading about HHEnumeartion-xcode in The iOS Times.

**Comment by huaxi** [comment]
oh,thanks to call my attention, let me try

**Comment by huaxi** [comment]
Thank you for your support，It's submitted now.
