### ISSUE TITLE
Alcatraz 安裝會失敗

### ISSUE THREAD

**Issue by chiahsien** [bugEnding/HHEnumeration-Xcode#5]
我用 Xcode 7.0，在 Alcatraz 裡頭，每次都安裝到一半就自動取消哩。

**Comment by huaxi** [comment]
已修复！
原因：刚开始在本地开发的时候，我取工程名为 HHEnumeration 的，后来上传了，仓库用了HHEnumeration-Xcode，用 Alcatraz 能远程下载到本地，就是没把工程运行起来，我想它大概是根据 插件名/仓库名 HHEnumeration-Xcode 来找工程，然而工程名是 HHEnumeration ，所以失败了。
解决：把工程名改成 HHEnumeration-Xcode ，完事！
谢谢支持！
![1 pic](https://cloud.githubusercontent.com/assets/14972862/10747696/2ece4d96-7c93-11e5-97ab-43cb08e043e6.jpg)
